services:
  db:
    image: postgres:18.3-alpine
    environment:
      POSTGRES_DB: product_recommendation_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  sonarqube:
    image: sonarqube:9.9-community
    ports:
      - "9000:9000"
    environment:
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs

  wiremock:
    image: wiremock/wiremock:3.13.2
    container_name: mock-api
    ports:
      - "8081:8080" # Access it at localhost:8081
    volumes:
      - ./wiremock/mappings:/home/wiremock/mappings
      - ./wiremock/__files:/home/wiremock/__files
    command: [ "--global-response-templating" ]

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    extra_hosts:
      - "host.docker.internal:host-gateway"

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin123
    volumes:
      - ./monitoring/grafana/dashboards/datasources:/etc/grafana/provisioning/datasources
      - ./monitoring/grafana/dashboards/dashboards:/etc/grafana/provisioning/dashboards
      - ./monitoring/grafana/dashboards/dashboards:/var/lib/grafana/dashboards

volumes:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
